version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install yarn
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn tsc
      - yarn vite build